# ─── Generated by npm run sync ───────────────────────────────────────────────

import datetime

# ─── Source ──────────────────────────────────────────────────────────────────

SERIES_ENDPOINT = "https://www.bankofengland.co.uk/boeapps/database/_iadb-fromshowcolumns.asp"

SERIES_CODE = "IUDBEDR"

SERIES_STARTS_ON = datetime.date(1975, 1, 2)

USER_AGENT = "uk-bank-rate (+https://github.com/BV-17/uk-bank-rate)"

# ─── Scheduled Decisions ─────────────────────────────────────────────────────

SCHEDULED_DECISION_DATES: tuple[datetime.date, ...] = (
    datetime.date(2026, 2, 5),
    datetime.date(2026, 3, 19),
    datetime.date(2026, 4, 30),
    datetime.date(2026, 6, 18),
    datetime.date(2026, 7, 30),
    datetime.date(2026, 9, 17),
    datetime.date(2026, 11, 5),
    datetime.date(2026, 12, 17),
    datetime.date(2027, 2, 4),
    datetime.date(2027, 3, 18),
    datetime.date(2027, 4, 29),
    datetime.date(2027, 6, 17),
    datetime.date(2027, 7, 29),
    datetime.date(2027, 9, 16),
    datetime.date(2027, 11, 4),
    datetime.date(2027, 12, 16),
)
