// ─── Node Standard Library ─────────────────────────────────────────────────

import { readFile, writeFile } from 'node:fs/promises';
import { relative } from 'node:path';
import { fileURLToPath } from 'node:url';

// ─── Paths ─────────────────────────────────────────────────────────────────

const ROOT = new URL('../', import.meta.url);
const at = (path) => new URL(path, ROOT);

const SHARED_CHANGES = at('shared/bank-rate-changes.json');
const SHARED_SCHEDULE = at('shared/scheduled-decisions.json');
const SHARED_SOURCE = at('shared/source.json');
const TYPESCRIPT_GENERATED = at('typescript/src/generated.ts');
const PYTHON_GENERATED = at('python/src/uk_bank_rate/_generated.py');
const PYTHON_GENERATED_HISTORY = at('python/src/uk_bank_rate/_generated_history.py');
const TYPESCRIPT_MANIFEST = at('typescript/package.json');
const TYPESCRIPT_LOCKFILE = at('typescript/package-lock.json');
const README = at('README.md');
const PYTHON_VERSION = at('python/src/uk_bank_rate/_version.py');
const LICENCE = at('LICENSE');
const LICENCE_COPIES = [at('typescript/LICENSE'), at('python/LICENSE')];

// ─── Validation ────────────────────────────────────────────────────────────

const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;
const DECIMAL = /^-?\d+(?:\.\d+)?$/;

const fail = (message) => {
  throw new Error(message);
};

const validateChanges = ({ changes, observedTo }) => {
  changes.forEach(([date, rate], index) => {
    if (!ISO_DATE.test(date)) fail(`change ${index}: ${date} is not an ISO date`);
    if (!DECIMAL.test(rate)) fail(`change ${index}: ${rate} is not a decimal string`);
    const previous = changes[index - 1];
    if (previous && previous[0] >= date) fail(`change ${index}: ${date} does not follow ${previous[0]}`);
    if (previous && previous[1] === rate) fail(`change ${index}: ${rate} repeats the rate before it`);
  });
  const last = changes.at(-1);
  if (!ISO_DATE.test(observedTo) || !last || observedTo < last[0]) fail('observedTo must be an ISO date on or after the last change');
};

const validateSchedule = ({ dates }) => {
  dates.forEach((date, index) => {
    if (!ISO_DATE.test(date)) fail(`scheduled decision ${index}: ${date} is not an ISO date`);
    if (index > 0 && dates[index - 1] >= date) fail(`scheduled decision ${index}: ${date} does not follow ${dates[index - 1]}`);
  });
};

const validateSource = ({ endpoint, seriesCode, seriesStartsOn, userAgent }) => {
  if (!/^https:\/\//.test(endpoint)) fail('source endpoint must be an https URL');
  if (!/^[A-Z0-9]+$/.test(seriesCode)) fail('source seriesCode must be a Database series code');
  if (!ISO_DATE.test(seriesStartsOn)) fail('source seriesStartsOn must be an ISO date');
  if (!userAgent || /["'\\]/.test(userAgent)) fail('source userAgent must be set and hold no quotes');
};

const validateVersions = async () => {
  const lockfile = JSON.parse(await readFile(TYPESCRIPT_LOCKFILE, 'utf8'));
  const versions = {
    'typescript/package.json': JSON.parse(await readFile(TYPESCRIPT_MANIFEST, 'utf8')).version,
    'typescript/package-lock.json': lockfile.version,
    'typescript/package-lock.json packages[""]': lockfile.packages?.['']?.version,
    'python/src/uk_bank_rate/_version.py': /^VERSION = "([^"]+)"$/m.exec(await readFile(PYTHON_VERSION, 'utf8'))?.[1],
    'the README Version badge': /badge\/Version-([0-9.]+)-/.exec(await readFile(README, 'utf8'))?.[1],
  };
  if (new Set(Object.values(versions)).size !== 1) {
    fail(`the versions disagree:\n${Object.entries(versions).map(([where, version]) => `  ${where}: ${version}`).join('\n')}`);
  }
};

// ─── Rendering ─────────────────────────────────────────────────────────────

const HEADER_WIDTH = 78;

const header = (marker, label) => `${marker} ─── ${label} ${'─'.repeat(HEADER_WIDTH - marker.length - label.length - 6)}`;

const pythonDate = (isoDate) => {
  const [year, month, day] = isoDate.split('-').map(Number);
  return `datetime.date(${year}, ${month}, ${day})`;
};

const typescriptSource = ({ changes, observedTo }, { dates }, source) => [
  header('//', 'Generated by npm run sync'),
  '',
  "import type { BankRateHistory } from './types.js';",
  '',
  header('//', 'Source'),
  '',
  `export const SERIES_ENDPOINT = '${source.endpoint}';`,
  '',
  `export const SERIES_CODE = '${source.seriesCode}';`,
  '',
  `export const SERIES_STARTS_ON = '${source.seriesStartsOn}';`,
  '',
  `export const USER_AGENT = '${source.userAgent}';`,
  '',
  header('//', 'Scheduled Decisions'),
  '',
  'export const SCHEDULED_DECISIONS: readonly string[] = Object.freeze([',
  ...dates.map((date) => `  '${date}',`),
  ']);',
  '',
  header('//', 'Bank Rate Changes'),
  '',
  'const CHANGES: readonly (readonly [string, number])[] = [',
  ...changes.map(([date, rate]) => `  ['${date}', ${rate}],`),
  '];',
  '',
  header('//', 'Bundled History'),
  '',
  'export const bundledHistory: BankRateHistory = Object.freeze({',
  `  observedTo: '${observedTo}',`,
  '  changes: Object.freeze(CHANGES.map(([date, rate]) => Object.freeze({ date, rate }))),',
  '});',
  '',
].join('\n');

const pythonSource = ({ dates }, source) => [
  header('#', 'Generated by npm run sync'),
  '',
  'import datetime',
  '',
  header('#', 'Source'),
  '',
  `SERIES_ENDPOINT = "${source.endpoint}"`,
  '',
  `SERIES_CODE = "${source.seriesCode}"`,
  '',
  `SERIES_STARTS_ON = ${pythonDate(source.seriesStartsOn)}`,
  '',
  `USER_AGENT = "${source.userAgent}"`,
  '',
  header('#', 'Scheduled Decisions'),
  '',
  'SCHEDULED_DECISION_DATES: tuple[datetime.date, ...] = (',
  ...dates.map((date) => `    ${pythonDate(date)},`),
  ')',
  '',
].join('\n');

const pythonHistorySource = ({ changes, observedTo }) => [
  header('#', 'Generated by npm run sync'),
  '',
  'import datetime',
  'from decimal import Decimal',
  '',
  header('#', 'Bank Rate Changes'),
  '',
  'BUNDLED_CHANGES: tuple[tuple[datetime.date, Decimal], ...] = (',
  ...changes.map(([date, rate]) => `    (${pythonDate(date)}, Decimal("${rate}")),`),
  ')',
  '',
  `BUNDLED_OBSERVED_TO = ${pythonDate(observedTo)}`,
  '',
].join('\n');

// ─── Sync ──────────────────────────────────────────────────────────────────

const checkOnly = process.argv.includes('--check');
const changes = JSON.parse(await readFile(SHARED_CHANGES, 'utf8'));
const schedule = JSON.parse(await readFile(SHARED_SCHEDULE, 'utf8'));
const source = JSON.parse(await readFile(SHARED_SOURCE, 'utf8'));
validateChanges(changes);
validateSchedule(schedule);
validateSource(source);
await validateVersions();

const licence = await readFile(LICENCE, 'utf8');
const targets = [
  [TYPESCRIPT_GENERATED, typescriptSource(changes, schedule, source)],
  [PYTHON_GENERATED, pythonSource(schedule, source)],
  [PYTHON_GENERATED_HISTORY, pythonHistorySource(changes)],
  ...LICENCE_COPIES.map((copy) => [copy, licence]),
];

const stale = [];
for (const [target, content] of targets) {
  const current = await readFile(target, 'utf8').catch(() => null);
  if (current === content) continue;
  if (checkOnly) stale.push(relative(fileURLToPath(ROOT), fileURLToPath(target)));
  else await writeFile(target, content);
}

if (stale.length > 0) {
  process.stderr.write(`Out of step with shared/, so run npm run sync:\n${stale.map((path) => `  ${path}`).join('\n')}\n`);
  process.exit(1);
}

process.stdout.write(checkOnly
  ? 'Every generated file matches shared/\n'
  : `Synced ${changes.changes.length} changes and ${schedule.dates.length} scheduled decisions\n`);
