// ─── Node Standard Library ──────────────────────────────────────────────────

import { readFile, writeFile } from 'node:fs/promises';
import { relative } from 'node:path';
import { fileURLToPath } from 'node:url';

// ─── Paths ──────────────────────────────────────────────────────────────────

const ROOT = new URL('../', import.meta.url);
const at = (path) => new URL(path, ROOT);

const SHARED_CHANGES = at('shared/bank-rate-changes.json');
const SHARED_SCHEDULE = at('shared/scheduled-decisions.json');
const TYPESCRIPT_GENERATED = at('typescript/src/generated.ts');
const PYTHON_GENERATED = at('python/src/uk_bank_rate/_generated.py');
const TYPESCRIPT_MANIFEST = at('typescript/package.json');
const PYTHON_VERSION = at('python/src/uk_bank_rate/_version.py');
const LICENCE = at('LICENSE');
const LICENCE_COPIES = [at('typescript/LICENSE'), at('python/LICENSE')];

// ─── Validation ─────────────────────────────────────────────────────────────

const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;
const DECIMAL = /^-?\d+(?:\.\d+)?$/;

const fail = (message) => {
  throw new Error(message);
};

const validateChanges = ({ changes, observedTo }) => {
  changes.forEach(([date, rate], index) => {
    if (!ISO_DATE.test(date)) fail(`change ${index}: ${date} is not an ISO date`);
    if (!DECIMAL.test(rate)) fail(`change ${index}: ${rate} is not a decimal string`);
    const previous = changes[index - 1];
    if (previous && previous[0] >= date) fail(`change ${index}: ${date} does not follow ${previous[0]}`);
    if (previous && previous[1] === rate) fail(`change ${index}: ${rate} repeats the rate before it`);
  });
  const last = changes.at(-1);
  if (!ISO_DATE.test(observedTo) || !last || observedTo < last[0]) fail('observedTo must be an ISO date on or after the last change');
};

const validateSchedule = ({ dates }) => {
  dates.forEach((date, index) => {
    if (!ISO_DATE.test(date)) fail(`scheduled decision ${index}: ${date} is not an ISO date`);
    if (index > 0 && dates[index - 1] >= date) fail(`scheduled decision ${index}: ${date} does not follow ${dates[index - 1]}`);
  });
};

const validateVersions = async () => {
  const manifestVersion = JSON.parse(await readFile(TYPESCRIPT_MANIFEST, 'utf8')).version;
  const pythonVersion = /^VERSION = "([^"]+)"$/m.exec(await readFile(PYTHON_VERSION, 'utf8'))?.[1];
  if (manifestVersion !== pythonVersion) {
    fail(`typescript/package.json is ${manifestVersion} but python/src/uk_bank_rate/_version.py is ${pythonVersion}`);
  }
};

// ─── Rendering ──────────────────────────────────────────────────────────────

const HEADER_WIDTH = 79;

const header = (marker, label) => `${marker} ─── ${label} ${'─'.repeat(HEADER_WIDTH - marker.length - label.length - 6)}`;

const pythonDate = (isoDate) => {
  const [year, month, day] = isoDate.split('-').map(Number);
  return `datetime.date(${year}, ${month}, ${day})`;
};

const typescriptSource = ({ changes, observedTo }, { dates }) => [
  header('//', 'Generated by npm run sync'),
  '',
  "import type { BankRateHistory } from './types.js';",
  '',
  header('//', 'Scheduled Decisions'),
  '',
  'export const SCHEDULED_DECISIONS: readonly string[] = [',
  ...dates.map((date) => `  '${date}',`),
  '];',
  '',
  header('//', 'Bank Rate Changes'),
  '',
  'const CHANGES: readonly (readonly [string, number])[] = [',
  ...changes.map(([date, rate]) => `  ['${date}', ${rate}],`),
  '];',
  '',
  header('//', 'Bundled History'),
  '',
  'export const bundledHistory: BankRateHistory = {',
  `  observedTo: '${observedTo}',`,
  '  changes: CHANGES.map(([date, rate]) => ({ date, rate })),',
  '};',
  '',
].join('\n');

const pythonSource = ({ changes, observedTo }, { dates }) => [
  header('#', 'Generated by npm run sync'),
  '',
  'import datetime',
  'from decimal import Decimal',
  '',
  header('#', 'Scheduled Decisions'),
  '',
  'SCHEDULED_DECISION_DATES: tuple[datetime.date, ...] = (',
  ...dates.map((date) => `    ${pythonDate(date)},`),
  ')',
  '',
  header('#', 'Bank Rate Changes'),
  '',
  'BUNDLED_CHANGES: tuple[tuple[datetime.date, Decimal], ...] = (',
  ...changes.map(([date, rate]) => `    (${pythonDate(date)}, Decimal("${rate}")),`),
  ')',
  '',
  `BUNDLED_OBSERVED_TO = ${pythonDate(observedTo)}`,
  '',
].join('\n');

// ─── Sync ───────────────────────────────────────────────────────────────────

const checkOnly = process.argv.includes('--check');
const changes = JSON.parse(await readFile(SHARED_CHANGES, 'utf8'));
const schedule = JSON.parse(await readFile(SHARED_SCHEDULE, 'utf8'));
validateChanges(changes);
validateSchedule(schedule);
await validateVersions();

const licence = await readFile(LICENCE, 'utf8');
const targets = [
  [TYPESCRIPT_GENERATED, typescriptSource(changes, schedule)],
  [PYTHON_GENERATED, pythonSource(changes, schedule)],
  ...LICENCE_COPIES.map((copy) => [copy, licence]),
];

const stale = [];
for (const [target, content] of targets) {
  const current = await readFile(target, 'utf8').catch(() => null);
  if (current === content) continue;
  if (checkOnly) stale.push(relative(fileURLToPath(ROOT), fileURLToPath(target)));
  else await writeFile(target, content);
}

if (stale.length > 0) {
  process.stderr.write(`Out of step with shared/, so run npm run sync:\n${stale.map((path) => `  ${path}`).join('\n')}\n`);
  process.exit(1);
}

process.stdout.write(checkOnly
  ? 'Every generated file matches shared/\n'
  : `Synced ${changes.changes.length} changes and ${schedule.dates.length} scheduled decisions\n`);
